name: Deploy to GitHub Pages

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.x"
          channel: "any"

      - name: Build Web
        working-directory: ./example
        run: |
          flutter --version
          flutter pub get
          flutter build web --no-tree-shake-icons --base-href "flutter_confetti"

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./example/build/web

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
